WorkflowError in line 10 of /DATA/usr/m.trauernicht/projects/SuRE-TF/gen-2_mES/raw-data-analysis/Snakefile_12:
Failed to open /DATA/usr/m.trauernicht/projects/SuRE-TF/gen-2_stimulation-2/raw-data-analysis/config.py.
  File "/DATA/usr/m.trauernicht/projects/SuRE-TF/gen-2_mES/raw-data-analysis/Snakefile_12", line 10, in <module>
